### ISSUE TITLE
Don't rely on goIsrael azure account for images

### ISSUE THREAD

**Issue by kaplanlior** [CIOIL/nopcommerce-elastic-search-plugin#3]
This files has code the relies on https://info-goisrael-com.azureedge.net

./Views/GsaSearch/_EventProductBox.cshtml
./Views/GsaSearch/_ExchangeProductBox.cshtml
./Views/GsaSearch/_ForecastProductBox.cshtml
./Views/GsaSearch/_GeneralProductBox.cshtml
./Views/GsaSearch/_HotelProductBox.cshtml
./Views/GsaSearch/_NewGoIsraelProductBox.cshtml
./Views/GsaSearch/_PictureProductBox.cshtml

This should be an independent & generic plugin.

**Comment by ronenaTourism** [comment]
Thanks for your comment – we have fixed the code.
