### ISSUE TITLE
Please set a license for this repository

### ISSUE THREAD

**Issue by kaplanlior** [CIOIL/nopcommerce-elastic-search-plugin#4]
This is important if you want to call it an Open Source project, other wise, it's just public code.

Also, the government procedure to release code requires setting a license: https://www.gov.il/BlobFolder/policy/government_owned_code_publishing_policy/he/Government%20owned%20code%20publishing%20policy.pdf

**Comment by AmirPaz** [comment]
Thank you @kaplanlior the license has been added to the repository
